### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by BernardinD** [zye1996/Yolov5_EdgeTPU#1]
Hi, your repo looks great and I'm trying to replicate you success but looks like you did some external installations. You mention in your README that you plan to include installation instructions. Will those be available sometime soon?

**Comment by BernardinD** [comment]
The main hurdle was the tflite_utils.h/cpp. After removing them everything was smooth for the most part

**Comment by zye1996** [comment]
> The main hurdle was the tflite_utils.h/cpp. After removing them everything was smooth for the most part

Thanks for the input. Those files require tensorflow lite static library to work. I will add installation instruciton soon
