### ISSUE TITLE
How to run the executable ?

### ISSUE THREAD

**Issue by zlg9folira** [zye1996/Yolov5_EdgeTPU#2]
@zye1996 Thanks for publishing this. I built the repo and now am trying to run your demo. However, I don't quite get last part of your README. 
```
out/k8/Yolo_EdgeTpu
```
I built the project in folder `build`
```
../out/k8/Yolo_EdgeTpu: cannot execute binary file: Exec format error
```

UPDATE: I realized it is set to create a subdirectory with CPU arch name, which in my case was not `k8`. So I got the executable built in `out/aarch64/`. Running `./Yolo_EdgeTpu --model_path=../../model/yolo***.tflite`, I get 
```
ERROR: '/home/yzy/CLionProjects/Yolo_EdgeTPU/model/coco-labels.csv' not found!
```

It is seems the label file path is hard coded. I would suggest @zye1996 to update the repo with these little corrections. I am posting for anyone who ran into the same issues.

- In `src/main.cpp`, argument  `/home/yzy/CLionProjects/Yolo_EdgeTPU/model/coco-labels.csv` to be replaced with `../../model/coco-labels.csv`. 
- In `src/main.cpp`, default model path to be changed from `model/yolov5s6-int8_edgetpu.tflite` to `../../model/yolov5s6-int8_edgetpu.tflite`.

With this changes, it should work. (replace `{ARCH}` with the actual folder name)
```
cd out/{ARCH}/
./Yolo_EdgeTPU
```

**Comment by zye1996** [comment]
> @zye1996 Thanks for publishing this. I built the repo and now am trying to run your demo. However, I don't quite get last part of your README. 
> 
> ```
> 
> out/k8/Yolo_EdgeTpu
> 
> ```
> 
> I built the project in folder `build`
> 
> ```
> 
> ../out/k8/Yolo_EdgeTpu: cannot execute binary file: Exec format error
> 
> ```
> 
> 
> 
> UPDATE: I realized it is set to create a subdirectory with CPU arch name, which in my case was not `k8`. So I got the executable built in `out/aarch64/`. Running `./Yolo_EdgeTpu --model_path=../../model/yolo***.tflite`, I get 
> 
> ```
> 
> ERROR: '/home/yzy/CLionProjects/Yolo_EdgeTPU/model/coco-labels.csv' not found!
> 
> ```
> 
> 
> 
> It is seems the label file path is hard coded. I would suggest @zye1996 to update the repo with these little corrections. I am posting for anyone who ran into the same issues.
> 
> 
> 
> - In `src/main.cpp`, argument  `/home/yzy/CLionProjects/Yolo_EdgeTPU/model/coco-labels.csv` to be replaced with `../../model/coco-labels.csv`. 
> 
> - In `src/main.cpp`, default model path to be changed from `model/yolov5s6-int8_edgetpu.tflite` to `../../model/yolov5s6-int8_edgetpu.tflite`.
> 
> 
> 
> With this changes, it should work. (replace `{ARCH}` with the actual folder name)
> 
> ```
> 
> cd out/{ARCH}/
> 
> ./Yolo_EdgeTPU
> 
> ```

Yes you are right. I will update the repo. The model file is not hard coded. You can feed argument through commandline. Check options with --help flag

**Comment by zye1996** [comment]
fixed the demo, closed
