### ISSUE TITLE
The version 14 compiler of libedgetpu

### ISSUE THREAD

**Issue by tyouritsugun** [zye1996/Yolov5_EdgeTPU#3]
Hi,

Thank you very much for your source code. I can ran it without any problem. However, I met a problem when I tried to substitute the model to the newest one.

I am using the command below to convert the model to tflite for edgetpu as described in 
https://github.com/zldrobit/yolov5
```
git clone https://github.com/ultralytics/yolov5.git
cd yolov5
python export.py --weights yolov5s.pt --include tflite --int8 --img 320 --data data/coco128.yaml
```
Then I replaced the converted yolov5s-int8_edgetpu.tflite in your source code, but it complained that the model file version is 14 yet the runtime is 13. 

So I upgraded `libedgetpu` folder to the newest. After that, when I run the compiled `Yolo_EdgeTPU` with the appropriated parameters as before, the program terminated at line 76 of `YoloDecoder.cpp`.

Do you have some hints to solve this problem?

Thank you in advance

Tyou

**Comment by zye1996** [comment]
> Hi,
> 
> Thank you very much for your source code. I can ran it without any problem. However, I met a problem when I tried to substitute the model to the newest one.
> 
> I am using the command below to convert the model to tflite for edgetpu as described in https://github.com/zldrobit/yolov5
> 
> ```
> git clone https://github.com/ultralytics/yolov5.git
> cd yolov5
> python export.py --weights yolov5s.pt --include tflite --int8 --img 320 --data data/coco128.yaml
> ```
> 
> Then I replaced the converted yolov5s-int8_edgetpu.tflite in your source code, but it complained that the model file version is 14 yet the runtime is 13.
> 
> So I upgraded `libedgetpu` folder to the newest. After that, when I run the compiled `Yolo_EdgeTPU` with the appropriated parameters as before, the program terminated at line 76 of `YoloDecoder.cpp`.
> 
> Do you have some hints to solve this problem?
> 
> Thank you in advance
> 
> Tyou

You need to make sure the tensorflow-lite.a library matches the the version when libedgetpu is compiled.
